<<<<<<< HEAD
title: General Contractor | Island Park | Teton Valley | Rexburg
email: jared@jbkayconstruction.com
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: General Contractor | Island Park | Teton Valley | Rexburg
email: jared@jbkayconstruction.com
description: Custom high end Construction based in Rexburg Idaho. Servicing Island Park, Teton Valley, and Rexburg.  Custom homes and cabins.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jbkayconstruction.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
>>>>>>> slate
